### ISSUE TITLE
libdxcompiler.dylib  - dxcompiler library not loaded

### ISSUE THREAD

**Issue by OttoHatt** [nicebyte/niceshade#26]
Building from source and attempting to compile a shader, I get "dxcompiler library not loaded".

I'm on an M1 MacBook Air. I replaced `libdxcompiler.dylib` with the one bundled in LunarG's VulkanSDK, then it worked just fine. I'm not familiar with Mac development - is this an x86/Arm architecture issue, a security thing..?

Adding the system's VulkanSDK environment variable to the candidates list would future-proof this, but it's not as portable.

**Comment by nicebyte** [comment]
it sounds like it may be an m1 vs x86 issue. Currently, all users of niceshade that build for apple platforms run the shader compilation step on Intel Macs (even if the final target for the shaders to run on is apple silicon).

I'll look into providing binaries targeting both architectures.

**Comment by dBagrat** [comment]
Fixed in https://github.com/nicebyte/niceshade/pull/28
